apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: Jenkins-E3
spec:
  selector: 
    app: jenkins
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
